

<div class="header">
		<a href="AddaSalesRecord.php">  <img class="pic" src="../styles/images/logo.png" alt="My logo"/></a>
			<div class="sidenav">
				<ul>
					<a href="AddaSalesRecord.php">New Sales</a>
					<a href="EditaSalesRecord.php">Edit Sales</a>
					<a href="DisplaySaleRecord.php">Display Record</a>
					<a href="ViewMonthlySalesReport.php">Dispay Report</a>
					<a href="AddaSalesRecord.php">logOut</a>
					<a href="javascript:void(0);" class="icon" onclick="myFunction()">
						<i class="fa fa-bars"></i>
					</a>
				</ul>
			</div>	
</div>
			
			